### ISSUE TITLE
French translation of UMM

### ISSUE THREAD

**Issue by patrickpollet** [jleyva/umm#3]
Hi Juan,

I have put on gist git://gist.github.com/1704282.git  the french translation file fr.json for UMM . 

If you want to incorporate it ;-) 

Nice job BTW and a very nice example of a HTML5 mobile app ! 

Cheers

**Comment by jleyva** [comment]
Merci beacoup Patrick, I just added the file

On Mon, Jan 30, 2012 at 2:04 PM, patrickpollet <
reply@reply.github.com

**Comment by patrickpollet** [comment]
Great,

   You just forgot to update lib/common.js ;-)

**Comment by jleyva** [comment]
Wow, you are absolutely right

https://github.com/jleyva/umm/commit/f1f1a5f77de9b10b90ff80733b6e8c79a88abecd

Sorry

On Mon, Jan 30, 2012 at 4:45 PM, patrickpollet <
reply@reply.github.com
